### ISSUE TITLE
指纹识别，很多error

### ISSUE THREAD

**Issue by lizhiyou88** [jwt1399/Sec-Tools#10]
![image](https://user-images.githubusercontent.com/39184961/225274525-c2549750-71a5-45c5-a3cb-b97291bc5a9e.png)

报错：
2023-03-15 17:56:32 - fake_useragent - WARNING - Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/bro
wsers/0.1.11
Traceback (most recent call last):
  File "D:\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "D:\毕业设计\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
2023-03-15 17:56:53 - fake_useragent - WARNING - Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/bro
wsers/0.1.11
Traceback (most recent call last):
  File "D:\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "D:\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range

这是为什么 fake_useragent包版本fake-useragent==0.1.11

**Comment by lizhiyou88** [comment]
这个地址不能使用了吗？ https://fake-useragent.herokuapp.com/browsers/0.1.11
[LOG GetDomain]:  www.baidu.com
[LOG GetDomain]:  www.baidu.com
[LOG GetDomain]:  www.baidu.com
2023-03-15 18:24:31 - fake_useragent - WARNING - Error occurred during loading data. Trying to use cache server https://fake-useragent.herokuapp.com/browsers/0.1.11
Traceback (most recent call last):
  File "D:\毕业设计\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 154, in load
    for item in get_browsers(verify_ssl=verify_ssl):
  File "D:\S2022040基于Django的网络安全漏洞扫描检测系统\ls\venv\lib\site-packages\fake_useragent\utils.py", line 99, in get_browsers
    html = html.split('<table class="w3-table-all notranslate">')[1]
IndexError: list index out of range
----------------------------------------

**Comment by yys5014** [comment]
哥，我毕设也打算做这个类型，教教我这个咋部署

**Comment by lizhiyou88** [comment]
> 哥，我毕设也打算做这个类型，教教我这个咋部署
> 
> Brother, I also intend to do this type of graduation, teach me this how to deploy

可以的 875982537 扣扣

**Comment by striker41** [comment]
报错＋1   搞定了么

**Comment by InKu0721** [comment]
改了本地ua，但是还报错error

**Comment by 1dad5da** [comment]
毕设做这个，效果可以吗？
