### ISSUE TITLE
旁站检查的时候不出结果socket.timeout: timed out

### ISSUE THREAD

**Issue by lizhiyou88** [jwt1399/Sec-Tools#11]
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 59728)
Traceback (most recent call last):
  File "D:\python\Python39\lib\socketserver.py", line 683, in process_request_thread
    self.finish_request(request, client_address)
  File "D:\python\Python39\lib\socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "D:\python\Python39\lib\socketserver.py", line 747, in __init__
    self.handle()
  File "E:\PycharmProjects\代码调试\2023-03-15S2022040基于Django的网络安全漏洞扫描检测系统\S2022040基于Django的网络安全漏洞扫描检测系统\ls\env\lib\site-packages\django\core\servers\basehttp.py", line 174, in
 handle
    self.handle_one_request()
  File "E:\PycharmProjects\代码调试\2023-03-15S2022040基于Django的网络安全漏洞扫描检测系统\S2022040基于Django的网络安全漏洞扫描检测系统\ls\env\lib\site-packages\django\core\servers\basehttp.py", line 182, in
 handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "D:\python\Python39\lib\socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
----------------------------------------

这是什么原因

**Comment by striker41** [comment]
加1  求大佬指点

**Comment by striker41** [comment]
> 解决了吗

没解决，debug的时候看那个action好像是非空的但是还是显示No Action
![image](https://user-images.githubusercontent.com/57217751/232956641-92722eae-4edf-4943-b939-389e823aac9c.png)

**Comment by fh122890** [comment]
回复有点快啊

**Comment by fh122890** [comment]
你用的python3.7吗

**Comment by fh122890** [comment]
能加个好友不

**Comment by fh122890** [comment]
加个好友吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月19日(星期三) 中午11:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11)





  
解决了吗
  
没解决，debug的时候看那个action好像是非空的但是还是显示No Action

**Comment by striker41** [comment]
> 加个好友吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月19日(星期三) 中午11:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11) 解决了吗 没解决，debug的时候看那个action好像是非空的但是还是显示No Action — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
怎么加的呢

**Comment by fh122890** [comment]
1448404788




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月19日(星期三) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11)





  
加个好友吧
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月19日(星期三) 中午11:08 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11) 解决了吗 没解决，debug的时候看那个action好像是非空的但是还是显示No Action — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
 怎么加的呢

**Comment by fh122890** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jwt1399/Sec-Tools"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月19日(星期三) 中午11:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11)





  
加个好友吧
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: @.&gt;; 发送时间: 2023年4月19日(星期三) 中午11:08 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11) 解决了吗 没解决，debug的时候看那个action好像是非空的但是还是显示No Action — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***&gt;
 怎么加的呢
  
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;







看见QQ了吗

**Comment by lsptz** [comment]
> 加个好友吧
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月19日(星期三) 中午11:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [jwt1399/Sec-Tools] 旁站检查的时候不出结果socket.timeout: timed out (Issue #11) 解决了吗 没解决，debug的时候看那个action好像是非空的但是还是显示No Action — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;
解决了吗，大佬，教教我

**Comment by 10lyf** [comment]
解决了吗

**Comment by kk645** [comment]
来个大佬指点下
